### ISSUE TITLE
execute a option @ search duplicate

### ISSUE THREAD

**Issue by ashraful1980** [bytemare/ecdsa-keyrec#2]
Dear Sir,
Thanks for published ecdsa-keyrec software.

Could you please execute a option @ search duplicate :
Pay2PublicKey
Sign2MultiSig
Sign2KeyHash
Sign2ScriptHash
from tx_in.csv which found https://github.com/gcarq/rusty-blockparser

Thanks & Regards,
Ashraf

**Comment by bytemare** [comment]
Hi Ashraf,

I'm not sure I understand what you are asking for. Can you elaborate ?

**Comment by ashraful1980** [comment]
Dear Sir,
Thanks for your quick response.

Someone idea about the cracking private key as bellow:
**1 step** 
Dowloads rusty-blockparser
Windows, OS X and Linux. All you need is rust and cargo
Bitcoin, Litecoin, Dogecoin etc

Dowloads Bitcoin Core 230GB blochain


**Step 2** 
./blockparser -t 24 csvdump /path/to/dump/
tx_in.csv
txid ; hashPrevOut ; indexPrevOut ; scriptSig ; sequence


**Step 3**
Sreach script ! dupla pubkey
Pay2PublicKey
Sign2MultiSig
Sign2KeyHash
Sign2ScriptHash

**Step 4**
csvdump> Pay2PublicKey  PublicKey.file
WOOW !! PublicKey.txt 

woala xd
------------------------------------------

I have done step 1 & step 2; unfortunately i couldn't find way to work step 3 & step 4.
Could you please help me....


![image](https://user-images.githubusercontent.com/52574658/126890025-3d17f678-0570-40b4-b42c-d0778d14246d.png)

**Comment by bytemare** [comment]
I still do not understand what you are asking for. This repo helps you recover a private key if you give it two signatures from the same private key using the same nonce, nothing else.

**Comment by ashraful1980** [comment]
Dear Sir,
I asking to point that the possible to find reused R value from tx_in.csv file.

**Comment by bytemare** [comment]
The nonce value is the first half of the signature. So all you have to do is find two signatures that have the same first half of their signature.

**Comment by bytemare** [comment]
Closing the issue, since it is out of the scope of the repo.
