### ISSUE TITLE
Using your program for secp256k1 can you recover the private key?

### ISSUE THREAD

**Issue by demining** [bytemare/ecdsa-keyrec#3]
Using your program for secp256k1 can you recover the private key?

I would like to understand what format is this public key?

```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpuXtxRVM66Bs0wooq288G3VXUHlr
bFTkMdbFM+SVYaFySfyUggFwTNKiDuTayOpLQNF6ypapU3eXBnIkWdcqSw==
-----END PUBLIC KEY-----

```
[https://github.com/bytemare/ecdsa-keyrec/blob/master/tests/test1/pub.key](https://github.com/bytemare/ecdsa-keyrec/blob/master/tests/test1/pub.key)

**Comment by bytemare** [comment]
The key in that file is PEM encoded.

secp256k1 should be supported.
